"""user need confirm account

Revision ID: 013ecb8d0436
Revises: 06d728ba8845
Create Date: 2022-04-09 02:41:46.294707

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '013ecb8d0436'
down_revision = '06d728ba8845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
