"""more notifications

Revision ID: 1230a456800a
Revises: 838fdc2b4cc2
Create Date: 2022-04-07 19:08:06.259608

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1230a456800a'
down_revision = '838fdc2b4cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_follows_read_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_likes_read_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_followeds_posts_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_followeds_posts_read_time')
        batch_op.drop_column('last_likes_read_time')
        batch_op.drop_column('last_follows_read_time')

    # ### end Alembic commands ###
