"""add comments_likes table

Revision ID: 256eb4f57cd2
Revises: e243a757bf6a
Create Date: 2022-04-07 12:02:58.323913

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '256eb4f57cd2'
down_revision = 'e243a757bf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_likes',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('comment_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_likes')
    # ### end Alembic commands ###
