"""users jwt

Revision ID: 4e7e7eb8bfae
Revises: 82ba73587a1b
Create Date: 2022-04-04 14:12:35.273258

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4e7e7eb8bfae'
down_revision = '82ba73587a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DATETIME(), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    # ### end Alembic commands ###
