"""add followers

Revision ID: 7206f1f56e30
Revises: c9ea0d53f06f
Create Date: 2022-04-05 14:26:18.291717

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7206f1f56e30'
down_revision = 'c9ea0d53f06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
                    sa.Column('follower_id', sa.Integer(), nullable=True),
                    sa.Column('followed_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
