"""user add tokens

Revision ID: 82ba73587a1b
Revises: eab79b7d4bd4
Create Date: 2022-04-03 23:02:11.430473

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '82ba73587a1b'
down_revision = 'eab79b7d4bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
