"""add private messages

Revision ID: bb55489b9ab6
Revises: 1230a456800a
Create Date: 2022-04-07 21:11:09.231684

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bb55489b9ab6'
down_revision = '1230a456800a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('sender_id', sa.Integer(), nullable=True),
                    sa.Column('recipient_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'],
                                            name=op.f('fk_messages_recipient_id_users')),
                    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
                    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_messages_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_messages_read_time')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))

    op.drop_table('messages')
    # ### end Alembic commands ###
