"""add posts table

Revision ID: c9ea0d53f06f
Revises: bbf8d6924665
Create Date: 2022-04-05 12:07:34.709534

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c9ea0d53f06f'
down_revision = 'bbf8d6924665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('location', sa.String(length=64), nullable=True),
                    sa.Column('about_me', sa.Text(), nullable=True),
                    sa.Column('member_since', sa.DateTime(), nullable=True),
                    sa.Column('last_seen', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('summary', sa.Text(), nullable=True),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('views', sa.Integer(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
                    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('location', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('about_me', sa.TEXT(), nullable=True),
                    sa.Column('member_since', sa.DATETIME(), nullable=True),
                    sa.Column('last_seen', sa.DATETIME(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
